Homework-12
Otus-DevOps-2018-02/Dev0psPadawan_infra pull request #11
Opened 2018-07-27 02:54 UTC by Dev0psPadawan

# Выполнено ДЗ № 12

 - Основное ДЗ

## В процессе сделано:
 - Созданы ВМ при помощи Vagrant
 - Протестировал созданные ранее роли при помощи Molecule

## Как запустить проект:
 - Запустить команду vagrant up в директории ansible

## Как проверить работоспособность:
 - Перейти по ссылке http://10.10.20.10:9292

## PR checklisk
 -   Выставил label с номером домашнего задания
 -   Выставил label с темой домашнего задания

2018-08-13 11:09 UTC, grim-yawn requested changes
Закоммичена директория с окружением python, надо удалить

2018-08-13 11:38 UTC, Dev0psPadawan commented
Добавил  в  gitignore директории test-roles/lib*

2018-08-13 12:09 UTC, WeitBelou commented
Добавь, пожалуйста, в .gitignore всё окружение (test-roles) и удали его из индекса (например [так](https://stackoverflow.com/a/1274447)).

2018-08-13 12:12 UTC, grim-yawn requested changes
Добавь, пожалуйста, в .gitignore всё окружение (test-roles) и удали его из индекса (например [так](https://stackoverflow.com/a/1274447)).

2018-08-13 12:50 UTC, Dev0psPadawan commented
Готово

2018-08-13 13:26 UTC, grim-yawn requested changes
Всё вроде ок, но
* Надо разобраться с Pipfile/requirements.txt
* Тесты падают на этапе lint, надо поправить

2018-08-13 13:26 UTC, WeitBelou commented on Pipfile
> +[[source]]
Есть ещё requirements.txt. Хорошо бы их слить в один.

2018-08-13 16:27 UTC, Dev0psPadawan commented
Добавил версию python в ansible/requirements.txt
Не понял про тесты и lint. Можно поконкретнее описать что не так?

2018-08-14 08:23 UTC, grim-yawn commented
1) Имелось в виду
   ```
   [[source]]
   url = "https://pypi.org/simple"
   verify_ssl = true
   name = "pypi"

   [dev-packages]

   [packages]
   requests = "*"
   ansible = ">=2.4"
   molecule = ">=2.6"
   testinfra = ">=1.10"
   python-vagrant = ">=0.5.15"

   [requires]
   python_version = "2.7"
   ```
   но ок оно в принципе работало и до этого, единственная проблема была в том, что приходилось 
   сперва pipenv'ом делать окружение, а затем накатывать из requirements.txt зависимости

2) `molecule test` (не `verify`) запустит цепочку
    ```
    ├── lint
    ├── destroy
    ├── dependency
    ├── syntax
    ├── create
    ├── prepare
    ├── converge
    ├── idempotence
    ├── side_effect
    ├── verify
    └── destroy
    ```
    и сейчас оно фейлится на стадии `lint`

2018-09-24 14:52 UTC, grim-yawn approved these changes

2018-09-24 14:57 UTC, merged