Packer base
Otus-DevOps-2018-02/Dev0psPadawan_infra pull request #5
Opened 2018-03-27 17:00 UTC by Dev0psPadawan

# Выполнено ДЗ № 6

 -  Основное ДЗ
 -  Задание со *

## В процессе сделано:
 - Установлен Packer
 - Установлен Packer шаблон ubuntu16.json
 - Создана директория packer. Вся дальнейшая работа велась в ней.
 - Добавлены скрипты из предыдущего ДЗ в директорию scripts.
 - Созданы файлы переменных variables.json и variables.json.example.
 - Создан Packer шаблон immutable.json для создания ВМ с "запечёнными" зависимостями
приложения и самим кодом приложения
 - Создан файл puma.service для создания юнита в systemd https://gist.github.com/Dev0psPadawan/749536088d99877bff7a260ad2ccd324
 - Создан скрипт systemd_unit_create.sh в директории files для автоматического запуска puma.service.
 - Создан скрипт create-redditvm.sh в директории config-scripts для запуска ВМ с "запечёнными" зависимостями приложения и самим кодом приложения из командной строки

## Как запустить проект:
 - для основного ДЗ:
 packer build -var-file=variables.json ubuntu16.json
-для первого доп.ДЗ:
 packer build -var-file=variables.json immutable.json
-для второго доп.ДЗ:
systemd_unit_create.sh

## Как проверить работоспособность:
 - Например, перейти по ссылке http://ipaddress:9292

## PR checklisk
 -  Выставил label с номером домашнего задания
 -  Выставил label с темой домашнего задания

2018-04-01 18:27 UTC, Nklya requested changes
Добрый вечер.

Андрей, есть несколько проблем, которые нужно исправить:
1. Файл системд юнита скачивается в рантайме во время билда. Это плохой и неповторяемый процесс.
2. Шаблон immutable должен строится так же, как reddit-base, за исключением того, что в конце добавляется системд юнит и делается деплой. Еще лучше использовать в immutable в качестве базового reddit-base.
У тебя сейчас два шаблона генерятся совершенно по-разному.
3. В директории пакера все файлы должны быть в file, скрипты в скриптах.

Комментарии ниже.

2018-04-01 18:27 UTC, Nklya commented on packer/files/systemd_unit_create.sh
> +wget -P /etc/systemd/system/ https://gist.githubusercontent.com/Dev0psPadawan/749536088d99877bff7a260ad2ccd324/raw/01c0a5e05b09f777537aca444e3e56fee380f827/puma.service
Зачем эта дичь со скачиванием файла юнита из гистов в процессе билда.
Юнит должен уже лежать в `packer/files`

2018-04-01 18:27 UTC, Nklya commented on packer/variables.json.example
> +    "ssh_username": "appuser",
Если ты не собираешся переопределять все переменные в  `variables.json` файле, их можно просто указать в секции `"variables": {` шаблона, и в `variables.json` задать только то, что хочешь переопределить, или обязательные переменные, например имя проекта.

2018-04-01 18:27 UTC, Nklya commented on packer/files/systemd_unit_create.sh
> +#!/bin/bash
Почему этот скрипт в files?

2018-04-01 18:27 UTC, Nklya commented on packer/scripts/systemd_unit_create.sh
> +#!/bin/bash
Зачем 2 одинаковых скрипта и в files, и в scripts?

2018-04-01 18:27 UTC, Nklya commented on packer/immutable.json
> +    "source_image_family": "ubuntu-1604-lts",
Подсказка: если ты здесь укажешь `reddit-base`, то не надо будет заново ставить руби и монгу.

2018-04-01 18:27 UTC, Nklya commented on packer/immutable.json
> +      "type": "shell",
С чего вдруг для reddit-base используются install_ruby install_mongodb, а здесь появляется startup_script?

2018-04-01 18:27 UTC, Nklya commented on packer/immutable.json
> +      "script": "files/systemd_unit_create.sh",
Зачем этот странный  скрипт здесь, если здесь нужен только деплой?

2018-04-02 21:52 UTC, Dev0psPadawan commented
Приветствую. Благодарю за замечания. Пофиксил.

2018-04-06 08:46 UTC, Nklya approved these changes
Добрый день.

Много захардкоженых не самых лучших решений, но относительно ок.

Комментарии ниже.

2018-04-06 08:46 UTC, Nklya commented on packer/scripts/systemd_unit_create.sh
> +mv /home/scouserandrew/puma.service /etc/systemd/system/
Зачем хардкодить такое /home/scouserandrew/, если можно было просто в /tmp положить?

2018-04-06 08:46 UTC, Nklya commented on packer/scripts/systemd_unit_create.sh
> +cd /home/scouserandrew/reddit
Ты уже перешел в хоум в 5 строчке, здесь достаточно было бы `cd reddit`

2018-04-06 08:46 UTC, Nklya commented on packer/scripts/startup_script.sh
> +#!/bin/bash
Он теперь здесь как бы не нужен.

2018-04-06 17:55 UTC, merged