Homework-7
Otus-DevOps-2018-02/Dev0psPadawan_infra pull request #6
Opened 2018-04-01 15:57 UTC by Dev0psPadawan

# Выполнено ДЗ №

 - Основное ДЗ
 - Задание со *

## В процессе сделано:
 - Установлен terraform 
 - Определён провайдер GCP
 - Написаны конфиги для инициализации ВМ, создания правила файерволла, добавления ssh ключей.
 - Объявлены необходимые пользовательские переменные.

## Как запустить проект:
 - Выполнить terraform plan в дирректории terraform.

## Как проверить работоспособность:
 - Например, перейти по ссылке http://ipaddress:9292

## PR checklisk
 - Выставил label с номером домашнего задания
 - Выставил label с темой домашнего задания

2018-04-01 18:31 UTC, Nklya requested changes
Ревью после принятия предыдущего ДЗ и мержа в эту ветку мастера.

2018-04-06 08:49 UTC, Nklya commented
После мержа предыдущего PR не забудь подмержить мастер в эту ветку и прогнать тесты тревиса.

2018-04-06 19:15 UTC, Dev0psPadawan commented
Смержил, тесты прогнал.

2018-04-06 19:24 UTC, Nklya requested changes
Этот PR про 7-е ДЗ, т.е. первое про тераформ.

Здесь не появляется шаблонов пакера app.json db.json, и не разделяется еще конфигурация тераформа на app.tf и прочее.

Нужно вычистить из этого бранча следы следующего ДЗ.

2018-04-06 23:06 UTC, Dev0psPadawan commented
Уф... Сам запутался в своих же ветках и коммитах. Вроде теперь состояние правильное на момент сдачи этого ДЗ.

2018-04-07 05:17 UTC, Nklya approved these changes
Доброе утро.

Андрей, теперь все нормально.

У тебя в корне репозитория валяются файлы, которые в ДЗ с пакером должны были переехать в папку config-scripts.
В следующем ДЗ поправь это.

2018-04-07 05:17 UTC, Nklya commented on terraform/main.tf
> +  value = "${var.gcp_user1}:${file(pathexpand(var.public_key_path))}${var.gcp_user2}:${file(pathexpand(var.public_key_path))}"
Не думаю, что pathexpand здесь обязательно нужен.

2018-04-07 05:17 UTC, Nklya commented on terraform/main.tf.test
> +provider "google" {
Вот этот файл еще непонятно зачем остался.

2018-04-07 09:52 UTC, merged